### ISSUE TITLE
Starship, error on install

### ISSUE THREAD

**Issue by thejhobe** [eljef/dotfiles#1] opened 2022-06-19 14:10 UTC
Error when running /dotfiles/os/linux/distros/ubuntu/20.04/01.install_shartship.sh

 -| ** |-  curl --fail --location https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-musl.tar.gz --output /tmp/starship-x86_64-unknown-linux-musl.tar.gz
 -| ** |-  tar -xzf "/tmp/starship-x86_64-unknown-linux-musl.tar.gz" -C "/usr/local/bin"
 -| ** |-  chmod 755 /usr/local/bin/starship
 -| ** |-  rm /tmp/starship-x86_64-unknown-linux-musl.tar.gz

**Comment by eljef** [comment] 2022-06-22 03:21
I have not been able to reproduce this. I'll try in a few different VMs to see if I can get it to error out.

I assume you ran this as sudo? or root?

**Comment by thejhobe** [comment] 2022-06-22 10:25
I will try again later and confirm. This was on a fresh 22.04 install of Ubuntu Server.

**Comment by thejhobe** [comment] 2022-06-22 10:28
Can confirm, 


joel@optiplex:~/dotfiles/os/linux/distros/ubuntu/20.04$ sudo ./01_install_starship.sh
[sudo] password for joel:
 -| ** |-  curl --fail --location https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-musl.tar.gz --output /tmp/starship-x86_64-unknown-linux-musl.tar.gz
 -| ** |-  tar -xzf "/tmp/starship-x86_64-unknown-linux-musl.tar.gz" -C "/usr/local/bin"
 -| ** |-  chmod 755 /usr/local/bin/starship
 -| ** |-  rm /tmp/starship-x86_64-unknown-linux-musl.tar.gz

**Comment by eljef** [comment] 2022-06-27 19:41
I just looked at your latest comment. I don't see any error output. That is all normal output of the script.

You can confirm the existence of the starship binary with
`ls -ldah /usr/local/bin/starship`

**Comment by eljef** [comment] 2022-06-27 20:04
Thanks for letting me test on a system. I can't see any errors happening and confirmed the existence of the starship executable. Everything seems to be working as expected.

**Comment by eljef** [comment] 2022-06-27 20:05
Closing the issue since testing confirmed the script is working as expected.

**Closed as completed by eljef** 2022-06-27 20:05 UTC
Labels: bug
